# Generated by Django 2.1.7 on 2019-02-28 13:45

import agency.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/images/AdvantagesImages')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdvantageListItemText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item_text', models.TextField()),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='agency.Advantage')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('title_image', models.ImageField(upload_to=agency.models.real_estate_title_image_path)),
                ('description', models.TextField()),
                ('square', models.IntegerField()),
                ('vendor_code', models.CharField(max_length=20)),
                ('is_hot_offer', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('purchase_or_rent', models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8)),
                ('number_of_rooms', models.IntegerField()),
                ('floor_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/images/ApartmentsImages')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('title_image', models.ImageField(upload_to=agency.models.real_estate_title_image_path)),
                ('description', models.TextField()),
                ('square', models.IntegerField()),
                ('vendor_code', models.CharField(max_length=20)),
                ('is_hot_offer', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('purchase_or_rent', models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/images/CommercialsImages')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.Commercial')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('working_days', models.CharField(max_length=100)),
                ('working_time', models.CharField(max_length=100)),
                ('break_time', models.CharField(max_length=100)),
                ('ogrn', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='agency.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='agency/images/FeedbacksImages')),
                ('feedback_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('title_image', models.ImageField(upload_to=agency.models.real_estate_title_image_path)),
                ('description', models.TextField()),
                ('square', models.IntegerField()),
                ('vendor_code', models.CharField(max_length=20)),
                ('is_hot_offer', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('purchase_or_rent', models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/images/GaragesImages')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.Garage')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('title_image', models.ImageField(upload_to=agency.models.real_estate_title_image_path)),
                ('description', models.TextField()),
                ('square', models.IntegerField()),
                ('vendor_code', models.CharField(max_length=20)),
                ('is_hot_offer', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('purchase_or_rent', models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8)),
                ('number_of_rooms', models.IntegerField()),
                ('floor_count', models.IntegerField()),
                ('house_type', models.CharField(choices=[('house', 'Дом'), ('country_house', 'Дача')], default='house', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/images/HousesImages')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.House')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('title_image', models.ImageField(upload_to=agency.models.real_estate_title_image_path)),
                ('description', models.TextField()),
                ('square', models.IntegerField()),
                ('vendor_code', models.CharField(max_length=20)),
                ('is_hot_offer', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('purchase_or_rent', models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/images/LandsImages')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.Land')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='agency/images/ProductCategoriesImages')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='agency/images/SocialNetworksImages')),
            ],
        ),
    ]
