# Generated by Django 2.1.7 on 2019-02-28 18:10

import agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20190228_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Вид преимущества', 'verbose_name_plural': 'Наши преимущества'},
        ),
        migrations.AlterModelOptions(
            name='advantagelistitemtext',
            options={'verbose_name': 'Пункт списка', 'verbose_name_plural': 'Описание преимущества'},
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='apartmentimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='commercial',
            options={'verbose_name': 'Коммерческая недвижимость', 'verbose_name_plural': 'Коммерческая недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='commercialimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='contactphone',
            options={'verbose_name': 'Номер телефон', 'verbose_name_plural': 'Номера телефонов'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'Гараж', 'verbose_name_plural': 'Гаражи'},
        ),
        migrations.AlterModelOptions(
            name='garageimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом/Дача', 'verbose_name_plural': 'Дома/Дачи'},
        ),
        migrations.AlterModelOptions(
            name='houseimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'verbose_name': 'Земля', 'verbose_name_plural': 'Земли'},
        ),
        migrations.AlterModelOptions(
            name='landimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Вид недвижимого имущества', 'verbose_name_plural': 'Виды недвижимого имущества'},
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.ImageField(upload_to='agency/images/AdvantagesImages', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='advantagelistitemtext',
            name='list_item_text',
            field=models.TextField(verbose_name='Пункт списка преимуществ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor_number',
            field=models.IntegerField(verbose_name='Номер этажа'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_hot_offer',
            field=models.BooleanField(default=False, verbose_name='Горячее предложение'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_rooms',
            field=models.IntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8, verbose_name='Продажа/Аренда'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square',
            field=models.IntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='vendor_code',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to=agency.models.real_estate_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='is_hot_offer',
            field=models.BooleanField(default=False, verbose_name='Горячее предложение'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8, verbose_name='Продажа/Аренда'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='square',
            field=models.IntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='vendor_code',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='commercialimage',
            name='image',
            field=models.ImageField(upload_to=agency.models.real_estate_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='break_time',
            field=models.CharField(max_length=100, verbose_name='Перерыв'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inn',
            field=models.CharField(max_length=100, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ogrn',
            field=models.CharField(max_length=100, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_days',
            field=models.CharField(max_length=100, verbose_name='Рабочие дни'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_time',
            field=models.CharField(max_length=100, verbose_name='Рабочее время'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(upload_to='agency/images/FeedbacksImages', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='is_hot_offer',
            field=models.BooleanField(default=False, verbose_name='Горячее предложение'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8, verbose_name='Продажа/Аренда'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='square',
            field=models.IntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='vendor_code',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='garageimage',
            name='image',
            field=models.ImageField(upload_to=agency.models.real_estate_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor_count',
            field=models.IntegerField(verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('house', 'Дом'), ('country_house', 'Дача')], default='house', max_length=8, verbose_name='Дом/Дача'),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_hot_offer',
            field=models.BooleanField(default=False, verbose_name='Горячее предложение'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_rooms',
            field=models.IntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='house',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8, verbose_name='Продажа/Аренда'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square',
            field=models.IntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='house',
            name='vendor_code',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to=agency.models.real_estate_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='land',
            name='is_hot_offer',
            field=models.BooleanField(default=False, verbose_name='Горячее предложение'),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='land',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда')], default='purchase', max_length=8, verbose_name='Продажа/Аренда'),
        ),
        migrations.AlterField(
            model_name='land',
            name='square',
            field=models.IntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='land',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='land',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='land',
            name='vendor_code',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='landimage',
            name='image',
            field=models.ImageField(upload_to=agency.models.real_estate_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(upload_to='agency/images/ProductCategoriesImages', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
