# Generated by Django 2.1.7 on 2019-02-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20190228_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='land',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
