# Generated by Django 2.1.7 on 2019-02-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20190228_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactphone',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
    ]
