# Generated by Django 2.1.7 on 2019-02-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20190228_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
