# Generated by Django 2.1.7 on 2019-03-01 10:03

import agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Титульное изображение'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Титульное изображение'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Титульное изображение'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Титульное изображение'),
        ),
        migrations.AlterField(
            model_name='land',
            name='title_image',
            field=models.ImageField(upload_to=agency.models.real_estate_title_image_path, verbose_name='Титульное изображение'),
        ),
    ]
