# Generated by Django 2.1.7 on 2019-03-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_auto_20190301_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_phone',
            field=models.CharField(default='', max_length=100, verbose_name='Номер телефона владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercial',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercial',
            name='owner_phone',
            field=models.CharField(default='', max_length=100, verbose_name='Номер телефона владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='owner_phone',
            field=models.CharField(default='', max_length=100, verbose_name='Номер телефона владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='owner_phone',
            field=models.CharField(default='', max_length=100, verbose_name='Номер телефона владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='owner_phone',
            field=models.CharField(default='', max_length=100, verbose_name='Номер телефона владельца'),
            preserve_default=False,
        ),
    ]
