# Generated by Django 2.1.7 on 2019-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_auto_20190301_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='archived', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='archived', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='garage',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AddField(
            model_name='garage',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='archived', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='house',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='archived', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='land',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AddField(
            model_name='land',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='archived', max_length=20, verbose_name='Статус'),
        ),
    ]
