# Generated by Django 2.1.7 on 2019-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_auto_20190301_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Титульный заголовок'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Титульный заголовок'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Титульный заголовок'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Титульный заголовок'),
        ),
        migrations.AlterField(
            model_name='land',
            name='title_text',
            field=models.CharField(max_length=100, verbose_name='Титульный заголовок'),
        ),
    ]
