# Generated by Django 2.1.7 on 2019-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_auto_20190301_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Титульный заголовок'),
        ),
    ]
