# Generated by Django 2.1.7 on 2019-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_auto_20190301_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве')], default='archived', max_length=20, verbose_name='Статус')),
                ('headline', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='agency/images/NewsImages', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('link_to_source', models.URLField(blank=True, verbose_name='Ссылка на источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
