# Generated by Django 2.1.7 on 2019-03-04 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
