# Generated by Django 2.1.7 on 2019-03-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_news_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/images/PartnersImages', verbose_name='Логотип')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
