# Generated by Django 2.1.7 on 2019-03-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(default='#', verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
