# Generated by Django 2.1.7 on 2019-03-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0021_auto_20190305_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
