# Generated by Django 2.1.7 on 2019-03-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_auto_20190306_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Вид преимущества', 'verbose_name_plural': 'Преимущества'},
        ),
    ]
