# Generated by Django 2.1.7 on 2019-03-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_auto_20190306_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='square_units',
            field=models.CharField(choices=[('square meters', 'м²'), ('hectares', 'га')], default='square meters', max_length=20, verbose_name='Единицы измерения площади'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='square_units',
            field=models.CharField(choices=[('square meters', 'м²'), ('hectares', 'га')], default='square meters', max_length=20, verbose_name='Единицы измерения площади'),
        ),
        migrations.AddField(
            model_name='garage',
            name='square_units',
            field=models.CharField(choices=[('square meters', 'м²'), ('hectares', 'га')], default='square meters', max_length=20, verbose_name='Единицы измерения площади'),
        ),
        migrations.AddField(
            model_name='house',
            name='square_units',
            field=models.CharField(choices=[('square meters', 'м²'), ('hectares', 'га')], default='square meters', max_length=20, verbose_name='Единицы измерения площади'),
        ),
        migrations.AddField(
            model_name='land',
            name='square_units',
            field=models.CharField(choices=[('square meters', 'м²'), ('hectares', 'га')], default='square meters', max_length=20, verbose_name='Единицы измерения площади'),
        ),
    ]
