# Generated by Django 2.1.7 on 2019-03-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0024_auto_20190306_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='square_units',
            new_name='area_units',
        ),
        migrations.RenameField(
            model_name='commercial',
            old_name='square_units',
            new_name='area_units',
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='square_units',
            new_name='area_units',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='square_units',
            new_name='area_units',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='square_units',
            new_name='area_units',
        ),
    ]
