# Generated by Django 2.1.7 on 2019-03-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0025_auto_20190306_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='vendor_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='vendor_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='vendor_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='house',
            name='vendor_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='land',
            name='vendor_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
    ]
