# Generated by Django 2.1.7 on 2019-03-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0026_auto_20190307_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Титульный заголовок услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Пункт списка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='agency.Service')),
            ],
            options={
                'verbose_name': 'Пункт списка',
                'verbose_name_plural': 'Описание услуги',
            },
        ),
        migrations.RenameModel(
            old_name='AdvantageListItemText',
            new_name='AdvantageListItem',
        ),
        migrations.RenameField(
            model_name='advantagelistitem',
            old_name='list_item_text',
            new_name='text',
        ),
    ]
