# Generated by Django 2.1.7 on 2019-03-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0027_auto_20190307_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanyBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Титульный заголовок')),
                ('image', models.ImageField(blank=True, upload_to='agency/images/AboutCompanyImages', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Блок описания',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.AlterField(
            model_name='advantagelistitem',
            name='text',
            field=models.TextField(verbose_name='Пункт списка'),
        ),
    ]
