# Generated by Django 2.1.7 on 2019-03-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0028_auto_20190307_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='title_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='commercial',
            old_name='title_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='title_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='title_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='title_image',
            new_name='image',
        ),
    ]
