# Generated by Django 2.1.7 on 2019-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_auto_20190309_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Ссылка'),
        ),
    ]
