# Generated by Django 2.1.7 on 2019-03-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0030_auto_20190310_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('house', 'Дом'), ('country_house', 'Дача')], default='house', max_length=13, verbose_name='Дом/Дача'),
        ),
    ]
