# Generated by Django 2.1.7 on 2019-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0031_auto_20190319_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='square',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='square',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='square',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='land',
            name='square',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Площадь'),
        ),
    ]
