# Generated by Django 2.1.7 on 2019-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0032_auto_20190319_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='published', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='published', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='published', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='published', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'В архиве'), ('application', 'Заявка пользователя')], default='published', max_length=20, verbose_name='Статус'),
        ),
    ]
