# Generated by Django 2.1.7 on 2019-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0033_auto_20190321_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(blank=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, upload_to='agency/images/FeedbacksImages', verbose_name='Фото'),
        ),
    ]
