# Generated by Django 2.1.7 on 2019-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0034_auto_20190321_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда'), ('swap', 'Обмен')], default='purchase', max_length=8, verbose_name='Вид сделки'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда'), ('swap', 'Обмен')], default='purchase', max_length=8, verbose_name='Вид сделки'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда'), ('swap', 'Обмен')], default='purchase', max_length=8, verbose_name='Вид сделки'),
        ),
        migrations.AlterField(
            model_name='house',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда'), ('swap', 'Обмен')], default='purchase', max_length=8, verbose_name='Вид сделки'),
        ),
        migrations.AlterField(
            model_name='land',
            name='purchase_or_rent',
            field=models.CharField(choices=[('purchase', 'Продажа'), ('rent', 'Аренда'), ('swap', 'Обмен')], default='purchase', max_length=8, verbose_name='Вид сделки'),
        ),
    ]
