# Generated by Django 2.1.7 on 2019-03-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0035_auto_20190324_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='purchase_or_rent',
            new_name='type_of_transaction',
        ),
        migrations.RenameField(
            model_name='commercial',
            old_name='purchase_or_rent',
            new_name='type_of_transaction',
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='purchase_or_rent',
            new_name='type_of_transaction',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='purchase_or_rent',
            new_name='type_of_transaction',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='purchase_or_rent',
            new_name='type_of_transaction',
        ),
    ]
