# Generated by Django 2.1.7 on 2019-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0036_auto_20190324_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inn',
            field=models.CharField(blank=True, max_length=100, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ogrn',
            field=models.CharField(blank=True, max_length=100, verbose_name='ОГРН'),
        ),
    ]
