# Generated by Django 2.1.7 on 2019-03-24 12:18

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0037_auto_20190324_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Фон',
                'verbose_name_plural': 'Фон',
            },
        ),
        migrations.CreateModel(
            name='BackgroundData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', colorful.fields.RGBColorField(verbose_name='Цвет')),
                ('background_image', models.ImageField(upload_to='agency/images/BackgroundImages', verbose_name='Изображение')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='agency.Background')),
            ],
            options={
                'verbose_name': 'Цвет и изображение',
                'verbose_name_plural': 'Цвет и изображение',
            },
        ),
    ]
