# Generated by Django 2.1.7 on 2019-03-24 12:26

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0038_background_backgrounddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgrounddata',
            name='background_color',
            field=colorful.fields.RGBColorField(default='#ffffff', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='backgrounddata',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='agency/images/BackgroundImages', verbose_name='Изображение'),
        ),
    ]
