# Generated by Django 2.1.7 on 2019-03-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0039_auto_20190324_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgrounddata',
            old_name='background_image',
            new_name='image',
        ),
    ]
